### ISSUE TITLE
The CTC plugins (mastodon-ctc-0.1.2) are incompatible with Mastodon v1.0.0-beta-28

### ISSUE THREAD

**Issue by aherbert** [CellTrackingChallenge/fiji-plugins#2]
As of 5-Feb-2024 the CTC plugins and Mastodon plugins distributed through the Fiji updater are incompatible.

When starting Mastodon v1.0.0-beta-28 the following stack trace is generated:
```
[WARNING] 2 exceptions occurred during plugin discovery.
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: org/mastodon/mamut/plugin/MamutPluginAppModel
	at org.mastodon.ctc.CTC_Plugins.setAppPluginModel(CTC_Plugins.java:56)
	at org.mastodon.mamut.ProjectModel.lambda$discoverPlugins$1(ProjectModel.java:208)
	at org.mastodon.app.plugin.PluginUtils.lambda$forEachDiscoveredPlugin$0(PluginUtils.java:63)
	at org.mastodon.app.plugin.PluginUtils.forEachDiscoveredPlugin(PluginUtils.java:96)
	at org.mastodon.app.plugin.PluginUtils.forEachDiscoveredPlugin(PluginUtils.java:64)
	at org.mastodon.mamut.ProjectModel.discoverPlugins(ProjectModel.java:211)
	at org.mastodon.mamut.ProjectModel.<init>(ProjectModel.java:132)
	at org.mastodon.mamut.ProjectModel.create(ProjectModel.java:250)
	at org.mastodon.mamut.io.ProjectLoader.open(ProjectLoader.java:193)
	at org.mastodon.mamut.launcher.LauncherUtil.openWithDialog(LauncherUtil.java:332)
	at org.mastodon.mamut.launcher.MastodonLauncher.lambda$loadMastodonProject$19(MastodonLauncher.java:556)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: org.mastodon.mamut.plugin.MamutPluginAppModel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 12 more
```

Disabling the CTC update site allows Mastodon to function as expected. With the CTC plugins installed it cannot open any new or existing Mastodon project. 

CTC update site provides:
```
mastodon-ctc-0.1.2.jar
```

Mastodon update site provides:
```
mastodon-1.0.0-beta-28.jar
```

I presume this is due to a binary incompatible API change in Mastodon. Hopefully the fix is a simple recompile with a compatible CTC change and redistribute.

Note: This may require a downstream change to the plugin discovery mechanism in Mastodon to catch errors, log them, but continue without the incompatible plugins. Currently Mastodon does not gracefully handle incompatible plugins.

Let me know if I should cascade this issue to Mastodon.

**Comment by aherbert** [comment]
Closing. A new issue has been created in the correct repository:

https://github.com/mastodon-sc/mastodon-ctc/issues/8
